apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: dev-platform-devbox

build:
  artifacts:
    - image: appimage
    
deploy:
  helm:
    releases:
      - name: dev-platform-devbox
        chartPath: charts/coder
        namespace: dev-platform-devbox
        createNamespace: true
        setValueTemplates:
          coder.coderImage: "{{.IMAGE_REPO_appimage}}/{{.IMAGE_TAG_appimage}}@{{.IMAGE_DIGEST_appimage}}"
        setValues:
          coder.workspace: ""
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: dev-platform-devbox-localstack
        remoteChart: localstack/localstack
        namespace: dev-platform-devbox
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: dev-platform-devbox 
    port: 8080
    localPort: 8000